services:
  # The app service
  app:
    # image: devops-todo-app-app:latest
    # image:
    build: . # look for Dockerfile in current directory
    container_name: devops-todo-app
    ports:
      - "3000:3000" # Localhost:3000 maps to container's 3000
    environment:
      # DB_USER: myuser   # Database username
      # DB_PASSWORD: mypassword
      # DB_HOST: db
      # DB_PORT: 5432
      # DB_NAME: todo_db
      # Replace 'localhost' with the service name 'local-postgres'
      DATABASE_URL: postgresql://myuser:mypassword@local-postgres:5432/todo_db?schema=public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - db  # wait for the database service to be ready 
      

  # The databse service
  db:
    image: postgres:16-alpine
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432" # Localhost:5432 maps to container's 5432
    volumes:
      - db_data:/var/lib/postgresql/data
      
# This saves the database data even if the container is removed
volumes:
  db_data: